import "./globals.css";
import Menu from './components/menu/menu';
import styles from './layout.module.css'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width,initial-scale=1.0" />
      </head>
      <body>
      <main className={styles.mainContainer}>
        <Menu/>
        {children}
      </main>
      </body>
    </html>
  );
}
